name: "Gradle Enterprise - Save Build Scan"
description: 'Save Gradle Enterprise build scan'

inputs:
  build-tool:
    description: 'Build tool [gradle|maven]'
    default: 'gradle'

runs:
  using: "composite"
  steps:
    - name: Init environment
      # Required as $HOME is not expanded in a classical env section
      id: set-env
      run: |
        if [[ "${{ inputs.build-tool }}" == "gradle" ]]
        then
            BUILD_TOOL_HOME=".gradle"
        else
            BUILD_TOOL_HOME=".m2/.gradle-enterprise"
        fi
        echo "BUILD_SCAN_DATA_DIR=$HOME/$BUILD_TOOL_HOME/build-scan-data/*" >> $GITHUB_ENV
        echo "BUILD_METADATA_DIR=$HOME/build-metadata/${{ inputs.build-tool }}" >> $GITHUB_ENV
        
        # create unique name for upload artifact
        echo "uuid=$(cat /proc/sys/kernel/random/uuid)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Save Build Metadata
      id: save-build-metadata
      run: |
        mkdir -p $BUILD_METADATA_DIR

        BUILD_RUN_ID=${{ github.run_id }}
        BUILD_SHA=${{ github.event.pull_request.head.sha }}
        BUILD_PR=${{ github.event.number }}

        cat <<EOT >> ~/build.properties
        BUILD_RUN_ID=$BUILD_RUN_ID
        BUILD_SHA=$BUILD_SHA
        BUILD_PR=$BUILD_PR
        EOT
        
        echo "BUILD_RUN_ID=$BUILD_RUN_ID" >> $GITHUB_OUTPUT
        echo "BUILD_SHA=$BUILD_SHA" >> $GITHUB_OUTPUT
        echo "BUILD_PR=$BUILD_PR" >> $GITHUB_OUTPUT
        
        cp -r $BUILD_SCAN_DATA_DIR $BUILD_METADATA_DIR
      shell: bash
    - name: Upload Build Metadata
      uses: actions/upload-artifact@v3
      with:
        name: build-metadata-${{ steps.save-build-metadata.outputs.BUILD_PR }}
        path: |
          ~/build.properties
    - name: Upload Build Metadata
      uses: actions/upload-artifact@v3
      with:
        name: build-metadata-${{ steps.save-build-metadata.outputs.BUILD_RUN_ID }}
        path: |
          ~/build.properties
    - name: Upload Build Scan
      uses: actions/upload-artifact@v3
      with:
        name: build-metadata-${{ inputs.build-tool }}-${{ steps.set-env.outputs.uuid }}
        path: |
          ~/build-metadata/${{ inputs.build-tool }}
