name: Build Scan Upload

on:
    workflow_run:
      workflows: ["Verify Build"]
      types: [completed]

jobs:
  verification:
    name: Build Scan Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Download Build Scan
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-verification.yml
          workflow_conclusion: completed
      - name: Copy scan data
        run: |
          mkdir -p ~/.gradle/build-scan-data/
          cp -r scan-metadata/* ~/.gradle/build-scan-data/
          ls -ltR ~/.gradle/build-scan-data/
      - name: Publish build scan
        run: ./gradlew buildScanPublishPrevious
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            let pr_number = Number(fs.readFileSync('pr_number/pr_number'));
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: '👋 Build Scan® published!'
            });
