name: PR Build Scan Upload

on:
  workflow_run:
    workflows: [ "PR Build" ]
    types: [ completed ]

jobs:
  publish-gradle-build-scans:
    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-upload-gradle.yml@v1
    secrets: inherit
  publish-maven-build-scans:
    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-upload-maven.yml@v1
    secrets: inherit
