name: PR Build

on: [ pull_request ]

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build -x signPluginMavenPublication -i -Porg.gradle.java.installations.auto-download=false
      - name: Save Build Metadata
        env:
          BUILD_SCAN_DATA_DIR: ~/.gradle/build-scan-data
        run: |
          mkdir -p ~/.gradle/build-scan-data
          BUILD_PROPERTIES="${{ env.BUILD_SCAN_DATA_DIR }}/build.properties"
          echo "BUILD_SHA=${{ github.event.pull_request.head.sha }}" > ~/.gradle/build-scan-data/build.properties
          echo "BUILD_PR=${{ github.event.number }}" >> ~/.gradle/build-scan-data/build.properties
          ls -ltR ~/.gradle/build-scan-data
          cat ~/.gradle/build-scan-data/build.properties
      - name: Upload Build Metadata
        uses: actions/upload-artifact@v3
        with:
          name: build-metadata
          path: |
            ~/.gradle/build-scan-data/
