name: PR Build Scan Upload

on:
    workflow_run:
      workflows: ["PR Build"]
      types: [completed]

concurrency:
    group: pr

jobs:
  verification:
    name: Build Scan Upload
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: Download Build Metadata
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-verification.yml
          workflow_conclusion: completed
      - name: Copy Build Metadata
        run: |
          ls -ltR build-metadata/
          mkdir -p ~/.gradle/build-scan-data/
          cp -r build-metadata/* ~/.gradle/build-scan-data/
      - name: Load Build metadata
        id: load-metadata
        run: |
          source build-metadata/build.properties
          echo "sha=$(echo ${BUILD_SHA})" >> $GITHUB_OUTPUT
          echo "pr=$(echo ${BUILD_PR})" >> $GITHUB_OUTPUT
      - name: Fetch Build Metadata
        uses: actions/github-script@v6
        env:
          sha: ${{ steps.load-metadata.outputs.sha }}
          pr: ${{ steps.load-metadata.outputs.pr }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            statusOK = true;
            const checkRuns = await github.request('GET /repos/${{ github.repository }}/commits/{ref}/check-runs', {
              ref: process.env.sha
            });
            for await (const cr of checkRuns.data.check_runs) {
              console.log('Validating check conclusion: ' + cr.name);
              console.log('Validating check conclusion: ' + cr.completed_at);
              console.log('Validating check conclusion: ' + cr.conclusion);
              if(cr.conclusion != 'success') {
                console.log('Discarding ' + branch + ' with check conclusion ' + cr.conclusion);
                statusOK = false;
              }
            }
      - name: Wait for TOS to be approved
        run: |
          let fs = require('fs');
          let prNumber = Number(fs.readFileSync('build-metadata/pr-number.txt'));
          CHECKS_LIST=$(gh api /repos/${{ github.repository }}issues/ --jq '.')
          echo $CHECKS_LIST
          exit 1
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish build scan
        run: ./gradlew buildScanPublishPrevious | tee build.out
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Capture Build Scan link
        id: capture-scan-link
        run: |
          echo "scan-link=$(grep -A1 "Publishing build scan..." build.out  | tail -n 1)" >> $GITHUB_OUTPUT
      - name: Comment PR
        uses: actions/github-script@v6
        env:
          pr: ${{ steps.load-metadata.outputs.pr }}
          scan-link: ${{ steps.capture-scan-link.outputs.scan-link }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: process.env.pr,
              owner: context.owner,
              repo: context.repo,
              body: `[Build Scan®](${process.env.scan-link})`
            })
