name: PR Build Scan Upload

on:
  workflow_run:
    workflows: [ "PR Build" ]
    types: [ completed ]
  issue_comment:
    types: [ created ]
#  pull_request_target:
#    types: [ opened,closed,synchronize ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Run Id
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.event.workflow_run.id = ${{ github.event.workflow_run.id }}"

#  GE-TOS:
#    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-tos.yml@v1
#    with:
#      path-to-document: 'https://gradle.com/legal/gradle-enterprise-software-agreement/'
#    secrets: inherit
#  publish-gradle-build-scans:
#    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-upload-gradle.yml@v1
#    secrets: inherit
#  publish-maven-build-scans:
#    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-upload-maven.yml@v1
#    secrets: inherit
