name: PR Build Scan Upload

on:
    workflow_run:
        workflows: [ "PR Build" ]
        types: [ completed ]

jobs:
    verification:
        name: Build Scan Upload
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            -   name: "Gradle Enterprise Build Scan upload"
                uses: jprinet/test-gradle/.github/actions/build-scan-upload@v1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    ge-access-key: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
            -   name: "Gradle Enterprise Build Scan upload for Maven"
                uses: jprinet/test-gradle/.github/actions/build-scan-upload@v1
                if: always()
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    ge-access-key: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
                    build-tool: "maven"
