name: PR Build Scan Upload

on:
  workflow_run:
    workflows: [ "PR Build" ]
    types: [ completed ]
  issue_comment:
    types: [ created ]
#  pull_request_target:
#    types: [ opened,closed,synchronize ]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      github-event-name: ${{ steps.collect-github-inputs.outputs.github-event-name }}
      github-workflow-run-id: ${{ steps.collect-github-inputs.outputs.github-workflow-run-id }}
      github-sha: ${{ steps.collect-github-inputs.outputs.github-sha }}
      github-pr: ${{ steps.collect-github-inputs.outputs.github-pr }}
    steps:
      - name: Collect Github inputs
        id: collect-github-inputs
        run: |
          echo "github-event-name=${{ github.event_name }}" >> "$GITHUB_OUTPUT"
          echo "github-workflow-run-id=${{ github.event.workflow_run.id }}" >> "$GITHUB_OUTPUT"
          echo "github-sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"
          echo "github-pr=${{ github.event.number }}" >> "$GITHUB_OUTPUT"

  consume:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - run: |
          echo "event = $EVENT"
          echo "run id = $RUNID"
          echo "sha = $SHA"
          echo "pr = $PR"
        env:
          EVENT: ${{ needs.init.outputs.github-event-name }}
          RUNID: ${{ needs.init.outputs.github-workflow-run-id }}
          SHA: ${{ needs.init.outputs.github-sha }}
          PR: ${{ needs.init.outputs.github-pr }}

          

#  GE-TOS:
#    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-tos.yml@v1
#    with:
#      path-to-document: 'https://gradle.com/legal/gradle-enterprise-software-agreement/'
#    secrets: inherit
#  publish-gradle-build-scans:
#    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-upload-gradle.yml@v1
#    secrets: inherit
#  publish-maven-build-scans:
#    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-upload-maven.yml@v1
#    secrets: inherit
