name: PR Build - Gradle

on: [ pull_request ]

jobs:
  init:
    name: Init
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup build scan capture
        uses: gradle/github-actions/build-scan-setup-gradle@v0.3
        with:
          wrapper-init: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle 1
        run: ./gradlew clean
      - name: Build with Gradle 2
        run: ./gradlew foo

  build:
    name: Build
    if: ${{ always() && !cancelled() }}
    needs: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup build scan capture
        uses: gradle/github-actions/build-scan-setup-gradle@v0.3
        with:
          wrapper-init: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle 1
        run: ./gradlew clean
      - name: Build with Gradle 2
        run: ./gradlew foo

  test-matrix:
    name: test-matrix
    if: ${{ always() && !cancelled() }}
    strategy:
      matrix:
        version: [ "3.15", "3.15.1", "3.16" ]
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup build scan capture
        uses: gradle/github-actions/build-scan-setup-gradle@v0.3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Replace GE version
        run: |
          sed -i 's/3.14.1/${{ matrix.version}}/g' .mvn/extensions.xml
          cat .mvn/extensions.xml
          scanCount=$(find ./scan-maven-*/ -type f -name 'scan.scan' | wc -l)
      - name: Build with Maven 1
        run: mvn clean
      - name: Build with Maven 2
        run: mvn foo
