name: PR Build Scan Upload

on:
    workflow_run:
      workflows: ["PR Build"]
      types: [completed]

concurrency:
    group: pr

jobs:
  verification:
    name: Build Scan Upload
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: Wait for TOS to be approved
        run: |
          CHECKS_LIST=$(gh api /repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs --jq '.check_runs.[]')
          echo $CHECKS_LIST
          exit 1
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Download Build Metadata
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-verification.yml
          workflow_conclusion: completed
      - name: Copy Build Metadata
        run: |
          ls -ltR build-metadata/
          mkdir -p ~/.gradle/build-scan-data/
          cp -r build-metadata/* ~/.gradle/build-scan-data/
      - name: Publish build scan
        run: ./gradlew buildScanPublishPrevious | tee build.out
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
      - name: Capture Build Scan link
        run: |
          grep -A1 "Publishing build scan..." build.out  | tail -n 1 > build-scan-link.txt
          cat build-scan-link.txt
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let prNumber = Number(fs.readFileSync('build-metadata/pr-number.txt'));
            let buildScanLink = fs.readFileSync('build-scan-link.txt');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `[Build Scan®](${buildScanLink})`
            });
