name: Build Scan Upload

on:
    workflow_run:
        workflows: ["Verify Build"]

jobs:
  verification:
    name: Build Scan Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Download Build Scan
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-verification.yml
          workflow_conclusion: completed
      - name: Copy data
        run: |
          mkdir -p ~/.gradle/build-scan-data/3.14.1/previous
          cp buildscan/* ~/.gradle/build-scan-data/3.14.1/previous
          ls -ltR ~/.gradle/build-scan-data/3.14.1/previous
      - name: Publish build scan
        run: ./gradlew buildScanPublishPrevious
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
