name: "Gradle Enterprise TOS"
on:
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened,closed,synchronize ]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  GE-TOS:
    uses: jprinet/test-gradle/.github/workflows/reusable-build-scan-tos.yml@v1
    with:
      path-to-document: 'https://gradle.com/legal/gradle-enterprise-software-agreement/'
    secrets: inherit
