name: 'Terms of Service approval verification'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  gradle-check-tos:
    uses: gradle/github-actions/.github/workflows/check-tos.yml@v0.1
#    secrets: inherit
